[package]
name = "rustic-time-sheets"
version = "0.1.3"
edition = "2021"
author = "gb270"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.7.2"
csv = "1.3.0"
chrono = "0.4.38"

[build-dependencies]
slint-build = "1.7.2"
